"use client";

// Generated by pdfx init.
// See: https://pdfx.akashpise.dev/installation#theming
//
// Provides runtime theme overrides via React context.
// Wrap a subtree in <PdfxThemeProvider theme={myTheme}> to override defaults.

import { type DependencyList, type ReactNode, createContext, useContext } from 'react';
import { theme as defaultTheme } from './pdfx-theme';
export { defaultTheme };

export type PdfxTheme = typeof defaultTheme;

export const PdfxThemeContext = createContext<PdfxTheme>(defaultTheme);


/**
 * Returns the active theme from context.
 *
 * When called outside a React render tree (for example in plain-function tests),
 * React may throw an invalid hook error. In that case we return defaultTheme.
 * Unexpected errors are re-thrown.
 */
export function usePdfxTheme(): PdfxTheme {
  const theme = useContext(PdfxThemeContext);
  return theme ?? defaultTheme;
}

/**
 * Calls factory() and returns the result.
 * The deps parameter is accepted for API compatibility with existing callers.
 */
export function useSafeMemo<T>(factory: () => T, _deps: DependencyList): T {
  return factory();
}
