
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const UserRole = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  RECEPTIONIST: 'RECEPTIONIST',
  TRAINER: 'TRAINER'
} as const

export type UserRole = (typeof UserRole)[keyof typeof UserRole]


export const MemberStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  SUSPENDED: 'SUSPENDED',
  DELETED: 'DELETED'
} as const

export type MemberStatus = (typeof MemberStatus)[keyof typeof MemberStatus]


export const Gender = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  OTHER: 'OTHER'
} as const

export type Gender = (typeof Gender)[keyof typeof Gender]


export const MembershipStatus = {
  ACTIVE: 'ACTIVE',
  EXPIRED: 'EXPIRED',
  FROZEN: 'FROZEN',
  CANCELLED: 'CANCELLED',
  PENDING: 'PENDING'
} as const

export type MembershipStatus = (typeof MembershipStatus)[keyof typeof MembershipStatus]


export const CheckInMethod = {
  QR: 'QR',
  NFC: 'NFC',
  PIN: 'PIN',
  MANUAL: 'MANUAL'
} as const

export type CheckInMethod = (typeof CheckInMethod)[keyof typeof CheckInMethod]


export const PaymentMethod = {
  CASH: 'CASH',
  CARD: 'CARD',
  TRANSFER: 'TRANSFER',
  YAPE: 'YAPE',
  PLIN: 'PLIN',
  CULQI: 'CULQI',
  MERCADOPAGO: 'MERCADOPAGO'
} as const

export type PaymentMethod = (typeof PaymentMethod)[keyof typeof PaymentMethod]


export const PaymentStatus = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED'
} as const

export type PaymentStatus = (typeof PaymentStatus)[keyof typeof PaymentStatus]


export const ClassStatus = {
  SCHEDULED: 'SCHEDULED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
} as const

export type ClassStatus = (typeof ClassStatus)[keyof typeof ClassStatus]


export const BookingStatus = {
  CONFIRMED: 'CONFIRMED',
  CANCELLED: 'CANCELLED',
  ATTENDED: 'ATTENDED',
  NO_SHOW: 'NO_SHOW'
} as const

export type BookingStatus = (typeof BookingStatus)[keyof typeof BookingStatus]


export const EquipmentStatus = {
  OPERATIONAL: 'OPERATIONAL',
  MAINTENANCE: 'MAINTENANCE',
  OUT_OF_SERVICE: 'OUT_OF_SERVICE'
} as const

export type EquipmentStatus = (typeof EquipmentStatus)[keyof typeof EquipmentStatus]


export const ConfigCategory = {
  TWILIO: 'TWILIO',
  RESEND: 'RESEND',
  PAYMENT: 'PAYMENT',
  UPLOADTHING: 'UPLOADTHING',
  GENERAL: 'GENERAL',
  NOTIFICATIONS: 'NOTIFICATIONS'
} as const

export type ConfigCategory = (typeof ConfigCategory)[keyof typeof ConfigCategory]


export const NotificationType = {
  WELCOME: 'WELCOME',
  MEMBERSHIP_EXPIRING: 'MEMBERSHIP_EXPIRING',
  MEMBERSHIP_EXPIRED: 'MEMBERSHIP_EXPIRED',
  PAYMENT_RECEIPT: 'PAYMENT_RECEIPT',
  PAYMENT_OVERDUE: 'PAYMENT_OVERDUE',
  CLASS_REMINDER: 'CLASS_REMINDER',
  CLASS_CANCELLED: 'CLASS_CANCELLED',
  CUSTOM: 'CUSTOM'
} as const

export type NotificationType = (typeof NotificationType)[keyof typeof NotificationType]


export const NotificationChannel = {
  EMAIL: 'EMAIL',
  SMS: 'SMS',
  BOTH: 'BOTH'
} as const

export type NotificationChannel = (typeof NotificationChannel)[keyof typeof NotificationChannel]


export const NotificationStatus = {
  PENDING: 'PENDING',
  SENT: 'SENT',
  FAILED: 'FAILED'
} as const

export type NotificationStatus = (typeof NotificationStatus)[keyof typeof NotificationStatus]
