
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/User'
export type * from './models/Session'
export type * from './models/Account'
export type * from './models/Verification'
export type * from './models/Member'
export type * from './models/BodyMetric'
export type * from './models/Plan'
export type * from './models/Membership'
export type * from './models/Attendance'
export type * from './models/Payment'
export type * from './models/Class'
export type * from './models/ClassBooking'
export type * from './models/Trainer'
export type * from './models/Equipment'
export type * from './models/SystemConfig'
export type * from './models/AuditLog'
export type * from './models/Notification'
export type * from './commonInputTypes'